### PR TITLE
fixing training and detection for meshes generated with the Reconstratio...

### PR DESCRIPTION
**Pull request by nlyubova**
...n pipeline

### CODE REVIEW

**Comment by vrabaud** [comment]
How come we did not see that before ? Any other upcoming fixes or I should release ?

**Comment by nlyubova** [comment]
Sorry, but now recognition of reconstructed meshes works well !

**Comment by vrabaud** [comment]
should I release that then ? any other bugfix coming up ? And please announce that on the mailing list with a screenshot :)

**Comment by nlyubova** [comment]
The next will be testing meshes in *.OBJ format (because of received
comments), but we can also release this version as a fix for reconstructed
meshes.

**Pull request merged**
