### PR TITLE
Patched linemod for kinect2 (using qhd)

### PR DESCRIPTION
**Pull request by vijendraxsingh**

### CODE REVIEW

**Comment by JimmyDaSilva** [comment]
@vijendra1125 This cannot be merged as it only works for the kinect2 and the QHD images as discussed in #28 
Making this change permanent within `linemod_detect.cpp` will prevent all xtion and kinect1 users to use linemod

We need a better way of handling this and for the mean time a separate branch could be enough. But we cannot just merge this to the master branch

**Comment by vijendraxsingh** [comment]
@JimmyDaSilva  Sure, I agree. I didn't create it with the intention of merging. I just wanted to have a separate branch of Linemod for Kinect V2 so that new users could directly use it. I am a beginner and I just felt that if it will have separate branch then it will be easy for people who are new to it.

**Comment by JimmyDaSilva** [comment]
@vijendra1125 Yeah that's nice, but won't be merged that way. Maybe @vrabaud could consider having a separate branch with that temporary fix instead

**Comment by vijendraxsingh** [comment]
@JimmyDaSilva Sure

**Pull request closed without merging**
